name: Update Visual Snapshots
on: [workflow_dispatch]
env:
  CI: true
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1 # Skip downloading during yarn install
  PLAYWRIGHT_BROWSERS_PATH: 0 # Places binaries to node_modules/@playwright/test

jobs:
  functional-tests:
    name: Functional
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: npx playwright install-deps
      - run: npm install
      - run: npx playwright install
      - run: npm run build
      - run: npm -w packages/dom run test:functional
      - uses: EndBug/add-and-commit@v7
        with:
          add: '.'
          author_name: 'GitHub Actions'
          author_email: 'github-actions@github.com'
          message: 'test: update visual snapshots'
